### ISSUE TITLE
API calls return 500 server error - no autoload.php file

### ISSUE THREAD

**Issue by whosgonna** [ictinnovations/ictcore#7]
The current git master appears to be broken.  Trying to make any API calls returns a 500 server error.  The problem seems to trace to this line in  /core/lib/init.php:

$loader = require dirname($path_core) . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php';

There is no vendor directory in this repository.

**Comment by tahiralmas** [comment]
Hi

The recommend way of  installation is RPM and Yum, Please use installation instruction from README.md to install ICTCore.

Regards

**Comment by whosgonna** [comment]
Is there any proper method to upgrade to the version in github?

My installation was from RPM, however API login failed.  This is because the API is just looking to match an md5 hash of the user's password to the record in the DB, however this method is obsoleted by Drupal.  I could probably submit a PR to fix this, but if i'm not working against a git repo this seems problematic.

**Comment by tahiralmas** [comment]
Drupal was never part of ICTCore! 
ICTCore use bearer token / jwt based authentication. so please update your setup accordingly.

Note: after updating by RPM you may need to run database upgrade script, which can be found in db directory.
